name: build_dev
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [ closed ]
jobs:
  build_job:
    name: build
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: ssh to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd ../nhantest/testdev
          git pull
          docker stop devdocker
          docker build . -t devdocker
          docker run -itd --rm --name devdocker -p 3358:80 devdocker
          docker rmi $(docker images --filter 'dangling=true' -q)
      
